# Generated by Django 5.0.6 on 2024-06-06 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
