# Generated by Django 5.0.6 on 2024-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
