# Generated by Django 5.0.6 on 2024-06-12 14:43

from django.db import migrations

def populate_usernames(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if not user.username:
            potential_username = user.email.split('@')[0]
        potential_suffix = 1
        while User.objects.filter(username=potential_username).exists():
            potential_username = f"{potential_username}_{potential_suffix}"
            potential_suffix += 1
        user.username = potential_username
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_usernames)
    ]
