# Generated by Django 5.0.6 on 2024-06-29 11:36

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0008_alter_user_nickname'), ('users', '0009_profile_usersettings_user_gender_user_profile_and_more'), ('users', '0010_alter_profile_bio'), ('users', '0011_remove_user_nickname')]

    dependencies = [
        ('users', '0007_user_populate_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('bio', models.TextField(default='')),
                ('is_nfsw_visible', models.BooleanField(default=False)),
                ('is_followable', models.BooleanField(default=True)),
                ('is_content_visible', models.BooleanField(default=True)),
                ('is_communities_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_lang', models.CharField(choices=[('en', 'English')], max_length=2)),
                ('location', models.CharField(choices=[('US', 'United States')], max_length=2)),
                ('is_beta', models.BooleanField(default=False)),
                ('is_over_18', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Non-binary'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.profile'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.usersettings'),
        ),
    ]
