# Generated by Django 5.0.6 on 2024-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_activity'),
        ('users', '0007_alter_user_username'),
    ]

    operations = [
    ]
