# Generated by Django 5.0.6 on 2024-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_post',
            field=models.BooleanField(default=True),
        ),
    ]
