# Generated by Django 5.0.6 on 2024-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_create_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
