# Generated by Django 5.0.6 on 2024-08-14 13:14

import django.db.models.deletion
import users.choices
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('is_nfsw_visible', models.BooleanField(default=False)),
                ('is_followable', models.BooleanField(default=True)),
                ('is_content_visible', models.BooleanField(default=True)),
                ('is_communities_visible', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Non-binary'), ('O', 'Other'), ('N', 'Non-specified')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociallink', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_lang', models.CharField(choices=[('en', 'English')], default='en', max_length=2)),
                ('location', models.CharField(choices=users.choices.get_locations, default='PL', max_length=2)),
                ('is_beta', models.BooleanField(default=False)),
                ('is_over_18', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
