# Generated by Django 5.0.6 on 2024-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_avatar'),
        ('users', '0010_user_warnings'),
    ]

    operations = [
    ]
