# Generated by JG 	2024-15-08 15:56:34

from django.db import migrations


def reverse(apps, schema_editor):
    pass


def add_empty_profiles_and_settings_to_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("users", "Profile")
    UserSettings = apps.get_model("users", "UserSettings")

    for user in User.objects.filter(profile=None):
        Profile.objects.create(user=user)
    
    for user in User.objects.filter(usersettings=None):
        UserSettings.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_sociallink_usersettings'),
    ]

    operations = [
        migrations.RunPython(add_empty_profiles_and_settings_to_users, reverse),
    ]