# Generated by Django 5.0.6 on 2024-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users_avatars/default.png', null=True, upload_to='users_avatars/'),
        ),
    ]
