# Generated by Django 5.0.6 on 2024-08-10 19:17

import users.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_profile_alter_user_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='content_lang',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='location',
            field=models.CharField(choices=users.choices.get_locations, default='PL', max_length=2),
        ),
    ]
