# Generated by Django 5.0.6 on 2024-07-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_0009_user_avatar_0010_user_warnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_post',
            new_name='can_create_post',
        ),
    ]
