# Generated by Django 5.1 on 2024-08-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_empty_user_profiles_and_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_nfsw_visible',
            new_name='is_nsfw_visible',
        ),
    ]
