# Generated by Django 5.0.6 on 2024-08-11 11:30

from django.db import migrations

def reverse(apps, schema_editor):
    pass

def add_empty_profiles_and_settings_to_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("users", "Profile")
    UserSettings = apps.get_model("users", "UserSettings")
    for user in User.objects.filter(profile=None):
        user.profile = Profile.objects.create()
        user.save()
    
    for user in User.objects.filter(user_settings=None):
        user.user_settings = UserSettings.objects.create()
        user.save()

def remove_unrelated_models(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    UserSettings = apps.get_model("users", "UserSettings")
    SocialLink = apps.get_model("users", "SocialLink")
    SocialLink.objects.filter(profile=None).delete()
    Profile.objects.filter(user=None).delete()
    UserSettings.objects.filter(user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usersettings_content_lang_and_more'),
    ]

    operations = [
        migrations.RunPython(add_empty_profiles_and_settings_to_users, reverse),
        migrations.RunPython(remove_unrelated_models, reverse),
    ]