# Generated by Django 5.0.6 on 2024-08-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_empty_user_profiles_and_settings'),
        ('users', '0012_alter_user_avatar'),
    ]

    operations = [
    ]
