# Generated by Django 5.1 on 2024-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_is_nfsw_visible_profile_is_nsfw_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma_score',
            field=models.IntegerField(default=0),
        ),
    ]
