# Generated by Django 5.0.6 on 2024-08-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_unrelated_profile_user_settings_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.usersettings'),
        ),
    ]
