# Generated by Django 5.0.6 on 2024-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='is_over_18',
            field=models.BooleanField(default=False),
        ),
    ]
