# Generated by Django 5.0.6 on 2024-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_create_post_user_can_create_post'),
        ('users', '0014_alter_user_avatar'),
    ]

    operations = [
    ]
