# Generated by Django 5.1 on 2024-08-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_nfsw_visible',
            new_name='is_nsfw_visible',
        ),
    ]
