# Generated by Django 5.1 on 2024-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma_score',
            field=models.IntegerField(default=0),
        ),
    ]
