# Generated by Django 5.0.6 on 2024-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20240825_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_create_post',
            field=models.BooleanField(default=True, help_text='Indicates whether the user can create posts. Defaults to True.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warnings',
            field=models.IntegerField(default=0, help_text='The number of warnings assigned to the user. Defaults to 0.'),
        ),
    ]
