# Generated by Django 5.1 on 2024-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_karma_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_nfsw_visible',
            new_name='is_nsfw_visible',
        ),
    ]
