# Generated by Django 5.0.6 on 2024-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_is_nfsw_visible_profile_is_nsfw_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_nsfw_visible',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='Profile contains content which is NSFW (may contain nudity, pornography, profanity, or inappropriate content for those under 18)'),
        ),
    ]
