# Generated by Django 5.1 on 2024-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_karma_score"),
        ("users", "0016_alter_user_can_create_post_alter_user_warnings"),
    ]

    operations = []
