# Generated by Django 5.1 on 2024-09-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_is_nsfw_visible_profile_is_nsfw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='karma_score',
            new_name='comment_karma',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_karma',
            field=models.IntegerField(default=0),
        ),
    ]
