# Generated by Django 5.1 on 2024-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_rename_is_nfsw_visible_profile_is_nsfw_visible"),
        ("users", "0017_merge_20240826_0824"),
    ]

    operations = []
