# Generated by Django 5.1 on 2024-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_karma_score_profile_comment_karma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gold_awards',
            field=models.IntegerField(default=0),
        ),
    ]
