# Generated by Django 5.0.6 on 2024-09-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_is_nsfw_visible_profile_is_nsfw'),
        ('users', '0018_merge_20240826_0836'),
    ]

    operations = [
    ]
