# Generated by Django 5.1 on 2024-09-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_karma_score_profile_comment_karma_and_more'),
        ('users', '0019_merge_20240901_1230'),
    ]

    operations = [
    ]
