# Generated by Django 5.1 on 2024-10-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_gold_awards'),
        ('users', '0020_merge_20240919_2146'),
    ]

    operations = [
    ]
