# Generated by Django 5.1 on 2024-10-25 11:40

import users.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_user_avatar_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='content_lang',
            field=models.CharField(choices=users.choices.get_languages, default='en', max_length=2),
        ),
    ]
