# Generated by Django 5.1 on 2024-10-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
