# Generated by Django 5.1 on 2024-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='revert_to_old_reddit',
            field=models.BooleanField(default=False),
        ),
    ]
