# Generated by Django 5.1 on 2024-11-22 17:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_usersettings_content_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.user_banner_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
