# Generated by Django 5.1 on 2024-12-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_profile_banner_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reactivate_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
