# Generated by Django 5.1.4 on 2024-12-22 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_user_deactivated_at_user_reactivate_until"),
        ("users", "0026_alter_profile_avatar_alter_profile_banner"),
    ]

    operations = []
