# Generated by Django 5.1.4 on 2024-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_merge_20241222_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
