# Generated by Django 5.1.4 on 2025-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_pending_email_user_pending_email_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
