# Generated by Django 5.1.4 on 2025-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_user_pending_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
