version: '2.0'

services:
  web:
    image: reddit:v0
    build: .
    ports:
      - "7000:8000"
    command:
      - /bin/sh
      - '-c'
      - '/code/entrypoint.sh'

    volumes:
      - .:/code
