# Generated by Django 5.0.6 on 2024-05-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_image_rename_type_postvote_choice_post_down_votes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="children",
                to="core.post",
            ),
        ),
    ]
