# Generated by Django 5.0.6 on 2024-05-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_post_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postvote",
            name="post",
        ),
        migrations.AddField(
            model_name="postvote",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_votes",
                to="core.post",
            ),
            preserve_default=False,
        ),
    ]
