# Generated by Django 5.0.6 on 2024-05-23 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_postvote_post_postvote_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postvote",
            unique_together={("post", "user")},
        ),
    ]
