# Generated by Django 5.0.6 on 2024-05-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_postvote_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.post",
            ),
            preserve_default=False,
        ),
    ]
