# Generated by Django 5.0.6 on 2024-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_image_options_remove_post_image_image_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(default=9999999),
        ),
    ]
