# Generated by Django 5.0.6 on 2024-05-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_image_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name_plural": "Communities"},
        ),
    ]
