# Generated by Django 5.0.6 on 2024-06-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_communitymember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="members",
            field=models.ManyToManyField(
                related_name="communities",
                through="core.CommunityMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="communitymember",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.community"
            ),
        ),
        migrations.AlterField(
            model_name="communitymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("100_member", "Member"),
                    ("200_moderator", "Moderator"),
                    ("300_admin", "Admin"),
                ],
                default="100_member",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="communitymember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
