# Generated by Django 5.0.6 on 2024-06-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_community_members_alter_communitymember_community_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
