# Generated by Django 5.0.6 on 2024-06-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_user_community_author_rename_user_post_author"),
        ("core", "0013_alter_savedpost_user"),
    ]

    operations = []
