# Generated by Django 5.0.6 on 2024-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_counter',
            field=models.IntegerField(default=0),
        ),
    ]
