# Generated by Django 5.0.6 on 2024-06-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_display_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
