# Generated by Django 5.0.6 on 2024-06-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_post_author'),
        ('core', '0018_alter_post_parent'),
    ]

    operations = [
    ]
