# Generated by Django 5.0.6 on 2024-06-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_community_managers_alter_post_managers'),
        ('core', '0019_merge_0018_alter_post_author_0018_alter_post_parent'),
    ]

    operations = [
    ]
