# Generated by Django 5.0.6 on 2024-06-24 19:18
from __future__ import unicode_literals

from django.db import migrations, transaction


def slugify_name(apps, schema_editor):
    Community = apps.get_model("core", "Community")

    with transaction.atomic():
        for community in Community.objects.all():
            if not community.slug:
                community.slug = community.generate_unique_slug()
                community.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_community_author'),
    ]

    operations = [
        migrations.RunPython(slugify_name),
    ]
