# Generated by Django 5.0.6 on 2024-08-18 09:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240624_2118'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('root_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
