# Generated by Django 5.0.6 on 2024-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240624_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_18_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('RESTRICTED', 'Restricted')], default='PUBLIC', max_length=10),
        ),
    ]
