# Generated by Django 5.0.6 on 2024-06-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_postreport_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='report_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreport',
            name='report_type',
            field=models.CharField(choices=[('BREAKS_RULES', 'Breaks r/fatFIRE rules'), ('EU_ILLEGAL_CONTENT', 'EU illegal content'), ('HARASSMENT', 'Harassment'), ('THREATENING_VIOLENCE', 'Threatening violence'), ('HATE', 'Hate'), ('MINOR_ABUSE_OR_SEXUALIZATION', 'Minor abuse or sexualization'), ('SHARING_PERSONAL_INFORMATION', 'Sharing personal information'), ('NON_CONSENSUAL_INTIMATE_MEDIA', 'Non-consensual intimate media'), ('PROHIBITED_TRANSACTION', 'Prohibited transaction'), ('IMPERSONATION', 'Impersonation'), ('COPYRIGHT_VIOLATION', 'Copyright violation'), ('TRADEMARK_VIOLATION', 'Trademark violation'), ('SELF_HARM_OR_SUICIDE', 'Self-harm or suicide'), ('SPAM', 'Spam')], max_length=50),
        ),
    ]
