# Generated by Django 5.0.6 on 2024-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_postreport_report_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
