# Generated by Django 5.0.6 on 2024-08-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_community_privacy'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
