# Generated by Django 5.0.6 on 2024-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240624_2118'),
        ('core', '0026_adminaction'),
    ]

    operations = [
    ]
