# Generated by Django 5.1 on 2024-09-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_post_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('11_REWARD', '15 points'), ('12_REWARD', '15 points'), ('13_REWARD', '15 points'), ('14_REWARD', '15 points'), ('15_REWARD', '15 points'), ('21_REWARD', '25 points'), ('22_REWARD', '25 points'), ('23_REWARD', '25 points'), ('24_REWARD', '25 points'), ('25_REWARD', '25 points'), ('31_REWARD', '50 points'), ('32_REWARD', '50 points'), ('33_REWARD', '50 points'), ('34_REWARD', '50 points'), ('35_REWARD', '50 points')], max_length=20)),
                ('gold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_awards', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
