# Generated by Django 5.0.6 on 2024-07-07 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_0022_auto_20240624_2118_0026_adminaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='comment',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreport',
            name='report_details',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
