# Generated by Django 5.1 on 2024-09-24 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_post_gold_postaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postaward',
            unique_together={('post', 'user')},
        ),
    ]
