# Generated by Django 5.0.6 on 2024-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_adminaction_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('BAN', 'Ban User'), ('DELETE', 'Delete Post'), ('WARN', 'Warn User'), ('ACCEPT', 'Accept')], max_length=10),
        ),
    ]
