# Generated by Django 5.1 on 2024-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_postaward_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaward',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
