# Generated by Django 5.0.6 on 2024-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_adminaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('BAN', 'Ban User'), ('DELETE', 'Delete Post'), ('WARN', 'Warn User'), ('DISMISS_REPORT', 'Dismiss Report')], max_length=16),
        ),
    ]
