# Generated by Django 5.1 on 2024-09-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_postaward_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postaward',
            old_name='user',
            new_name='giver',
        ),
        migrations.AlterUniqueTogether(
            name='postaward',
            unique_together={('post', 'giver')},
        ),
    ]
