# Generated by Django 5.0.6 on 2024-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_adminaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('10_BAN', 'Ban User'), ('20_DELETE', 'Delete Post'), ('30_WARN', 'Warn User'), ('40_DISMISS_REPORT', 'Dismiss Report')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='report_type',
            field=models.CharField(choices=[('10_BREAKS_RULES', 'Breaks r/fatFIRE rules'), ('20_EU_ILLEGAL_CONTENT', 'EU illegal content'), ('30_HARASSMENT', 'Harassment'), ('40_THREATENING_VIOLENCE', 'Threatening violence'), ('50_HATE', 'Hate'), ('60_MINOR_ABUSE_OR_SEXUALIZATION', 'Minor abuse or sexualization'), ('70_SHARING_PERSONAL_INFORMATION', 'Sharing personal information'), ('80_NON_CONSENSUAL_INTIMATE_MEDIA', 'Non-consensual intimate media'), ('90_PROHIBITED_TRANSACTION', 'Prohibited transaction'), ('100_IMPERSONATION', 'Impersonation'), ('110_COPYRIGHT_VIOLATION', 'Copyright violation'), ('120_TRADEMARK_VIOLATION', 'Trademark violation'), ('130_SELF_HARM_OR_SUICIDE', 'Self-harm or suicide'), ('140_SPAM', 'Spam')], max_length=50),
        ),
    ]
