# Generated by Django 5.0.6 on 2024-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_community_privacy'),
        ('core', '0031_alter_adminaction_action_and_more'),
    ]

    operations = [
    ]
