# Generated by Django 5.0.6 on 2024-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20240825_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='report_details',
            field=models.TextField(),
        ),
    ]
