# Generated by Django 5.0.6 on 2024-09-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_post_managers'),
        ('core', '0033_alter_postreport_report_details'),
    ]

    operations = [
    ]
