# Generated by Django 5.1 on 2024-10-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_postaward_receiver_alter_postaward_giver'),
        ('core', '0034_merge_20240901_1230'),
    ]

    operations = [
    ]
