# Generated by Django 5.1 on 2024-10-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20241004_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaward',
            name='choice',
            field=models.CharField(blank=True, choices=[], max_length=20),
        ),
    ]
