# Generated by Django 5.1 on 2024-10-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_postaward_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaward',
            name='choice',
            field=models.CharField(blank=True, choices=[('11_REWARD', '15 points'), ('12_REWARD', '15 points'), ('13_REWARD', '15 points'), ('14_REWARD', '15 points'), ('15_REWARD', '15 points'), ('21_REWARD', '25 points'), ('22_REWARD', '25 points'), ('23_REWARD', '25 points'), ('24_REWARD', '25 points'), ('25_REWARD', '25 points'), ('31_REWARD', '50 points'), ('32_REWARD', '50 points'), ('33_REWARD', '50 points'), ('34_REWARD', '50 points'), ('35_REWARD', '50 points')], max_length=20),
        ),
    ]
