# Generated by Django 5.1.4 on 2025-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
