# Generated by Django 5.1.4 on 2025-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_postvote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
