# Generated by Django 5.2 on 2025-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_postvote_updated_at_alter_postvote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square image, min 256×256px', null=True, upload_to='community_avatars/'),
        ),
        migrations.AddField(
            model_name='community',
            name='background',
            field=models.ImageField(blank=True, help_text='Recommended 1920×384px', null=True, upload_to='community_backgrounds/'),
        ),
    ]
