# Generated by Django 5.2 on 2025-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_community_avatar_community_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square image, min 256x256px', null=True, upload_to='community_avatars/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='background',
            field=models.ImageField(blank=True, help_text='Recommended 1920x384px', null=True, upload_to='community_backgrounds/'),
        ),
    ]
