from django.urls import path

from .views import (
    CommunityCreateView,
    CommunityDetailView,
    CommunityJoin,
    CommunityListView,
    CommunityUpdateView,
    ModeratorDashboardView,
    PostAwardCreateView,
    PostCreateView,
    PostDetailView,
    PostListView,
    PostReportedView,
    PostReportView,
    PostSaveView,
    PostVoteView,
    UserCommentEditView,
    UserPostDeleteView,
    UserPostEditView,
)

urlpatterns = [
    path("post-list/", PostListView.as_view(), name="post-list"),
    path("post-detail/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post-create/", PostCreateView.as_view(), name="post-create"),
    path("post/edit/<int:pk>/", UserPostEditView.as_view(), name="edit_post"),
    path("comment/edit/<int:pk>/", UserCommentEditView.as_view(), name="edit_comment"),
    path("post/delete/<int:pk>/", UserPostDeleteView.as_view(), name="delete_post"),
    path("post/<int:pk>/vote/<str:vote_type>/", PostVoteView.as_view(), name="post-vote"),
    path("post/<int:pk>/award/", PostAwardCreateView.as_view(), name="post-award"),
    path("post/<int:pk>/action/<str:action_type>/", PostSaveView.as_view(), name="post-save-unsave"),
    path("communities/", CommunityListView.as_view(), name="community-list"),
    path("community/create/", CommunityCreateView.as_view(), name="community-create"),
    path("community/<slug:slug>/", CommunityDetailView.as_view(), name="community-detail"),
    path("community/<slug:slug>/community-join", CommunityJoin.as_view(), name="community-join"),
    path("post/report/<int:pk>/", PostReportView.as_view(), name="post-report"),
    path("reported-post/<int:pk>/", PostReportedView.as_view(), name="reported-post"),
    path("community/<slug:slug>/update/", CommunityUpdateView.as_view(), name="community-update"),
    path("moderator-dashboard", ModeratorDashboardView.as_view(), name="moderator-dashboard"),
]
