name: 'code-review'
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]
jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: gvasilei/AutoReviewer@0.5.1
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_CODE_REVIEW_API_KEY }}
          model_name: "gpt-4"
          exclude_files: '*.json, *.md, *.yml' # optionally exclude files based on a wildcard expression. 