name: Run linting

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  pep8:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11"]
    if: github.event.pull_request.draft == false
    steps:
    - name: Cancel Previous Runs
      if: "!endsWith(github.ref, '/master') && !endsWith(github.ref, '/dev')"
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v3.2.0
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1
